version: 2

models:
- name: stg_addresses
  description: Contains user addresses
  columns:
      - name: address_id
        tests: 
          - unique
          - not_null
      - name: zipcode
        tests: 
          - positive_values

- name: stg_events
  description: Contains information about events on the platform like user viewing a page, adding an item to cart or checking out.
  columns:
      - name: event_id
        tests: 
          - unique
          - not_null
      - name: session_id
        tests: 
          - not_null
      - name: user_id
        tests: 
          - not_null      

- name: stg_order_items
  description: Contains information about the items in each order
  columns:
      - name: order_id
        tests: 
          - not_null
      - name: product_id
        tests: 
          - not_null  
      - name: quantity
        tests: 
          - positive_values           

- name: stg_orders
  description: Contains information about orders
  columns:
      - name: order_id
        tests: 
          - not_null
          - unique
      - name: user_id
        tests: 
          - not_null  
      - name: order_total
        tests: 
          - positive_values 
- name: stg_products
  description: Contains information about the products on the platform
  columns:
      - name: product_id
        tests: 
          - not_null
          - unique
      - name: name
        tests: 
          - not_null  
      - name: price
        tests: 
          - positive_values
          - not_null  
      - name: inventory
        tests: 
          - positive_values
          - not_null 
- name: stg_promos
  description: Contains information about active and inactive promo codes on the platform
  columns:
      - name: promo_id
        tests: 
          - not_null
          - unique
- name: stg_users
  description: Contains user information
  columns:
      - name: user_id
        tests: 
          - not_null
          - unique
      - name: first_name
        tests: 
          - not_null
      - name: last_name
        tests: 
          - not_null
      - name: email
        tests: 
          - not_null
          - unique
 